### ISSUE TITLE
Pass runner guidelines

### ISSUE THREAD

**Issue by ben-eb** [antono/jade-postcss#1]
[These rules are mandatory for PostCSS runners](https://github.com/postcss/postcss/blob/master/docs/guidelines/runner.md). I found the following issues:
- 2.1. Set from and to processing options
- 2.2. Use only the asynchronous API
- 3.1. Don’t show JS stack for CssSyntaxError
- 3.2. Display result.warnings()
- 3.3. Allow the user to write source maps to different files
- 4.2. Maintain a changelog
- 4.3. postcss-runner keyword in package.json

**Comment by antono** [comment]
Actually preferred way implement jade filter is jstransformer-\* module. Jade postcss should not be used.

**Comment by ben-eb** [comment]
OK, fair enough. :+1:
